Repository microsoft/graspologic, pull requests merged in 2020-09, with the labels that each got.

#438 Remove ari return value from AutoGMM.fit_predict
  graspy/cluster/base.py
Labels: ndd

#469 Brief warning about the merger in README for the time being
  README.md
Labels: docs, merger, pkg

#426 Fixes Documentation Build Warnings #291
  docs/conf.py
  docs/index.rst
  docs/release.rst
  docs/release/release_0.0.1.rst
  docs/release/release_0.0.2.rst
  docs/release/release_0.0.3.rst
  docs/release/release_0.1.rst
  docs/release/release_0.2.rst
  docs/release/release_0.3.rst
  docs/release/release_template.rst
  graspy/cluster/gclust.py
  graspy/embed/svd.py
  graspy/inference/latent_position_test.py
Labels: docs, ndd

#431 Remove * imports in simulations
  graspy/simulations/__init__.py
  tests/test_sims.py
Labels: ndd

#432 Fixes Add `n_iter_` attribute after fit to GraphMatch #342
  graspy/match/gmp.py
Labels: ndd

#433 Adds the Option to Concatenate Embeddings of Directed Graphs
  graspy/embed/ase.py
  graspy/embed/base.py
  graspy/embed/lse.py
  graspy/embed/mase.py
  graspy/embed/omni.py
  tests/test_base_embed.py
  tests/test_mase.py
  tests/test_omni.py
  tests/test_spectral_embed.py
Labels: ndd

#427 Add a link for the descriptions of `palette`
  docs/conf.py
  graspy/plot/plot.py
Labels: ndd

#462 Added n_features_in_ to three of the embedded class estimators (continued from #434)
  graspy/embed/ase.py
  graspy/embed/base.py
  graspy/embed/lse.py
  graspy/embed/mds.py
Labels: ndd
