Repository microsoft/graspologic, pull requests merged in 2020-11, with the labels that each got.

#569 Turn off codeowners
  .github/CODEOWNERS
Labels: pkg

#491 Adding MASE Tutorial
  docs/tutorial.rst
  docs/tutorials/embedding/MASE.ipynb
  docs/tutorials/embedding/Omnibus.ipynb
  graspologic/embed/mase.py
Labels: ndd

#518 Out of sample ASE
  docs/tutorial.rst
  docs/tutorials/embedding/AdjacencySpectralEmbed.ipynb
  docs/tutorials/embedding/OutOfSampleEmbed.ipynb
  graspologic/embed/ase.py
  graspologic/utils/__init__.py
  graspologic/utils/utils.py
  tests/test_sklearn.py
  tests/test_spectral_embed.py
  tests/test_utils.py
Labels: ndd

#593 add titles to heatmaps
  docs/tutorials/embedding/OutOfSampleEmbed.ipynb
Labels: enhancement, needs_reviewers, small, visualization

#578 Leiden and modularity
  CONTRIBUTING.md
  docs/reference/index.rst
  docs/reference/partition.rst
  docs/reference/utils.rst
  graspologic/__init__.py
  graspologic/partition/__init__.py
  graspologic/partition/leiden.py
  graspologic/partition/modularity.py
  graspologic/utils/__init__.py
  graspologic/utils/utils.py
  setup.py
  tests/partition/test_leiden.py
  tests/partition/test_modularity.py
  tests/test_data/large-graph-partitions.csv
  tests/test_data/large-graph.csv
  tests/test_utils.py
Labels: enhancement
