Repository microsoft/graspologic, pull requests merged in 2020-12, with the labels that each got.

#516 Clustering Tutorials
  docs/tutorial.rst
  docs/tutorials/clustering/autogmm.ipynb
  docs/tutorials/clustering/kclust.ipynb
Labels: ndd

#600 Update documentation location to RTD
  README.md
Labels: docs

#541 Pairplot with gmm functionality fixing #382
  docs/conf.py
  docs/reference/plotting.rst
  docs/tutorial.rst
  docs/tutorials/plotting/pairplot.ipynb
  docs/tutorials/plotting/pairplot_with_gmm.ipynb
  graspologic/plot/__init__.py
  graspologic/plot/plot.py
  setup.py
  tests/test_plot.py
  tests/test_rdpg_corr.py
Labels: ndd

#573 Create a simple tutorial for `Aligning`
  docs/tutorial.rst
  docs/tutorials/aligning/aligning.ipynb
Labels: ndd

#547 LPT/LDT implemented as a function
  docs/reference/inference.rst
  docs/tutorials/inference/latent_distribution_test.ipynb
  docs/tutorials/inference/latent_position_test.ipynb
  graspologic/inference/__init__.py
  graspologic/inference/base.py
  graspologic/inference/latent_distribution_test.py
  graspologic/inference/latent_position_test.py
  graspologic/version/version.txt
  setup.py
  tests/test_latentdistributiontest.py
  tests/test_latentpositiontest.py
Labels: ndd

#605 better comments in OOS tutorial
  docs/tutorials/embedding/OutOfSampleEmbed.ipynb
Labels: small

#562 Implement Vertex Nomination Via Seeded Graph Matching
  docs/reference/index.rst
  docs/reference/nominate.rst
  docs/tutorial.rst
  docs/tutorials/nominate/vertex_nomination_via_SGM.ipynb
  graspologic/nominate/VNviaSGM.py
  graspologic/nominate/__init__.py
  tests/test_vertex_nomination_via_SGM.py
Labels: ndd

#607 Change downloads count in Readme to cumulative from pepy
  README.md
Labels: docs, pkg, small

#619 Bug fixes for sklearn 0.24 compatibility
  tests/test_mug2vec.py
  tests/test_sklearn.py
Labels: bug, small

#616 Add "Roles" to top of repo
  CONTRIBUTING.md
  ROLES.md
Labels: docs, pkg
