Repository microsoft/graspologic, pull requests merged in 2021-01, with the labels that each got.

#620 Resolved the deprecation warning in AutoGMM
  graspologic/cluster/autogmm.py
Labels: bug

#611 Automatic Layouts and Rendering
  MANIFEST.in
  README.md
  docs/cli.rst
  docs/index.rst
  docs/reference/index.rst
  docs/reference/layouts.rst
  graspologic/layouts/__init__.py
  graspologic/layouts/__main__.py
  graspologic/layouts/auto.py
  graspologic/layouts/classes.py
  graspologic/layouts/colors.py
  graspologic/layouts/include/colors-100.json
  graspologic/layouts/nooverlap/__init__.py
  graspologic/layouts/nooverlap/_grid.py
  graspologic/layouts/nooverlap/_node.py
  graspologic/layouts/nooverlap/_quad_node.py
  graspologic/layouts/nooverlap/_quad_tree.py
  graspologic/layouts/nooverlap/nooverlap.py
  graspologic/layouts/render.py
  graspologic/preprocessing/graph_cuts.py
  setup.py
  tests/layouts/__init__.py
  tests/layouts/nooverlap/__init__.py
  tests/layouts/nooverlap/test_grid.py
  tests/layouts/nooverlap/test_grid_cell_creation.py
  tests/layouts/nooverlap/test_nooverlap.py
  tests/layouts/nooverlap/test_overlap_check.py
  tests/layouts/test_auto.py
Labels: enhancement

#561 Implemented mixed membership SBM sampling.
  docs/reference/simulations.rst
  docs/tutorial.rst
  docs/tutorials/simulations/mmsbm.ipynb
  docs/tutorials/simulations/sbm.ipynb
  graspologic/simulations/__init__.py
  graspologic/simulations/simulations.py
  tests/test_sims.py
Labels: ndd

#623 add pronouns and links to ROLES.md
  ROLES.md
Labels: docs, enhancement, pkg
